"""Add poster_url to movies

Revision ID: 2e80511c8736
Revises: 7ec8f0fdfba1
Create Date: 2025-01-11 21:43:33.780763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e80511c8736'
down_revision: Union[str, None] = '7ec8f0fdfba1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('poster_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'poster_url')
    # ### end Alembic commands ###
